###订单服务
server:
  port: 8200
###服务注册到eureka名称
spring:
    application:
        name: app-order
###当前会员服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

           
###在eureka显示服务
    register-with-eureka: true
###是否需要从eureka上获取注册信息
    fetch-registry: true
### 心跳检测与续约时间
### 测试时将值设置小些，保证服务关闭后注册中心能及时剔除服务
  instance:
  ###Eureka 客户端向服务端发送心跳的时间间隔，我单位为秒（客户端告诉服务端子机会按照规则）
    lease-renewal-interval-in-seconds: 1
  ##Eureka 服务端在收到最后一次心跳后等待的时间上限，单位为秒，超过规则则剔除
    lease-expiration-duration-in-seconds: 2
